### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by psiphi75** [fifthtry/realm#16]
This looks like a very interesting project and I would like to use it and possibly contribute to it.  However, it could have better user documentation. The basics would be:

- How to get an example running.
- How the front-end is laid out and how to enhance it.
- How the back-end is laid out and how to enhance it.
- How the front- and back-ends share state.

**Comment by amitu** [comment]
@psiphi75, am working on documentation :-)

**Comment by amitu** [comment]
The documentation of realm is being maintained no https://www.fifthtry.com/amitu/realm/. Fifthtry itself is powered by realm.

**Comment by amitu** [comment]
@psiphi75: I just finished writing a brief [Quickstart tutorial](https://www.fifthtry.com/amitu/realm/quick-start/) on realm, would love to get your feedback on it.
